# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e468af4c61e444f277b5a01c86e2c6cb7917696008f18535302f581168eced1a29f77a088f9ebd33c49599d9b7e29b32ff832ef05cd9e094e2f7aabbb59d802

test:
  secret_key_base: 46dd516eee6b92c2801fd9e86d83938ea37146838ac002f4f6e72cca349e42a095c8590de096336466ddb9f0a74b08869c8c11a7abdef6d53cc96bebf1e80999

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
